### PR TITLE
Add type mapping

### PR DESCRIPTION
**Pull request by thatrevguy**
Covers ints and floats. Similar to Elastic grok.

### CODE REVIEW

**Comment by thatrevguy** [comment]
Lint test fell over and died in Travis CI. Not sure why.

**Comment by tmessi** [comment]
I just updated the dev_requirements so now Travis should run the lint checks correctly. Update this with master, otherwise this looks good.

**Comment by thatrevguy** [comment]
Thank you for looking. Seems lint wants to be difficult or I'm not quite following instructions correctly.

**Comment by tmessi** [comment]
It looks like the lint ran correctly on travis this time, but now there are some actual lint issues in the code. The relevant output from Travis is:

```
************* Module yalp_grok.yalp_grok
C: 12, 0: Line too long (94/80) (line-too-long)
C: 21, 0: Line too long (85/80) (line-too-long)
C: 28, 0: Line too long (88/80) (line-too-long)
C: 29, 0: Line too long (101/80) (line-too-long)
C: 39, 0: Line too long (94/80) (line-too-long)
C: 60, 0: Line too long (111/80) (line-too-long)
C: 63, 0: Line too long (93/80) (line-too-long)
C: 92, 0: Line too long (111/80) (line-too-long)
C:153, 0: Line too long (115/80) (line-too-long)
C:178, 0: Line too long (117/80) (line-too-long)
C:150, 0: Missing function docstring (missing-docstring)
W:153,85: Cell variable pattern_format defined in loop (cell-var-from-loop)
C:161, 0: Missing function docstring (missing-docstring)
C:170, 0: Missing function docstring (missing-docstring)
C:181, 0: Missing function docstring (missing-docstring)
C:198, 0: Missing function docstring (missing-docstring)
C:206, 0: Missing function docstring (missing-docstring)
C:217, 0: Missing function docstring (missing-docstring)
W:219,15: Use of eval (eval-used)
```

You can run the linters locally with tox like this:

``` console
$ tox -e lint
```

**Comment by thatrevguy** [comment]
Lint is happy now

**Pull request merged**
